# Generated by Django 4.2.5 on 2023-10-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='fecha_publicacion',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(default=1, upload_to='articulos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
