# Generated by Django 4.2.5 on 2023-10-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_infoextra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='contenido',
            new_name='texto',
        ),
        migrations.AddField(
            model_name='articulo',
            name='subtitulo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
